### ISSUE TITLE
Need to install Freebase first？

### ISSUE THREAD

**Issue by shiyuxin2000** [reml-group/DoG#1]
Appreciate for your perfect work, and I tried to reproduce this work, but I found that the execurte_sparql in freebase_func always returned null. Should I install the Freebase first? And how to install it? Thank you!

**Comment by FlowingFrost** [comment]
Hi, did you find how to solve it? While running first python command in ReadMe, it told me the data was missing
  File "F:\CodingPrograms\DogAndToG\DoG-main\KBQA_TASK\metaqa\main_metaqa_1hop.py", line 27, in <module>
    with open('./data/metaqa_kg.pickle', 'rb') as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/metaqa_kg.pickle'

did you find the way to download database? Thank you for giving me advice
